version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # キャッシュを無効化するオプションを追加
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date +%Y-%m-%d)}
        - CACHEBUST=${CACHEBUST:-$(date +%s)}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # キャッシュを無効化するオプションを追加
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date +%Y-%m-%d)}
        - CACHEBUST=${CACHEBUST:-$(date +%s)}
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      # MySQLのオプションを更新
      command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ZERO_DATE,NO_ZERO_IN_DATE"
